### ISSUE TITLE
Getting error when using winrm, but it appears to be fully working

### ISSUE THREAD

**Issue by zdman135** [nsidc/vagrant-vsphere#146] opened 2015-08-27 19:26 UTC
vagrant is able to use the vsphere plugin and create a VM.
I am also able to run commands connected into the VM.
But for some reason, vagrant bombs out and thinks it's in a preparing state.

Let me know if I'm missing anything in my Vagrantfile.

Here is the console output from a vagrant up

==> default: Calling vSphere CloneVM with the following settings:
 INFO interface: info:  -- Template VM: testcenter/vm/WindowsTest
 INFO interface: info: ==> default:  -- Template VM: testcenter/vm/WindowsTest
==> default:  -- Template VM: testcenter/vm/WindowsTest
 INFO interface: info:  -- Target VM: testcenter/vm/anotherTest
 INFO interface: info: ==> default:  -- Target VM: testcenter/vm/anotherTest
==> default:  -- Target VM: testcenter/vm/anotherTest
 INFO machine: New machine ID: "42361eaa-5a92-d4ec-720f-9b019f2970f4"
 INFO interface: info: Waiting for WinRM to become available...
 INFO interface: info: ==> default: Waiting for WinRM to become available...
==> default: Waiting for WinRM to become available...
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: vsphere
 INFO machine: Calling action: get_ssh_info on provider vSphere (42361eaa-5a92-d4ec-720f-9b019f2970f4)
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_get_ssh_info #<Vagrant::Action::Builder:0x000001068fa8c0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000106921858>
 INFO warden: Calling IN action: #<VagrantPlugins::VSphere::Action::ConnectVSphere:0x00000106921808>
 INFO warden: Calling IN action: #<VagrantPlugins::VSphere::Action::GetSshInfo:0x00000106921790>
 INFO warden: Calling IN action: #<VagrantPlugins::VSphere::Action::CloseVSphere:0x00000106921718>
 INFO warden: Calling OUT action: #<VagrantPlugins::VSphere::Action::CloseVSphere:0x00000106921718>
 INFO warden: Calling OUT action: #<VagrantPlugins::VSphere::Action::GetSshInfo:0x00000106921790>
 INFO warden: Calling OUT action: #<VagrantPlugins::VSphere::Action::ConnectVSphere:0x00000106921808>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000106921858>
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000102af3770>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-57d6e3ef7bdf21436f4004068eeec058
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000102bfab00>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::VSphere::Errors::VSphereError: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.>
ERROR vagrant: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
ERROR vagrant: /Users/rich/.vagrant.d/gems/gems/vagrant-vsphere-1.4.0/lib/vSphere/action/connect_vsphere.rb:23:in `rescue in call'
/Users/rich/.vagrant.d/gems/gems/vagrant-vsphere-1.4.0/lib/vSphere/action/connect_vsphere.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
 INFO interface: error: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO interface: Machine: error-exit ["VagrantPlugins::VSphere::Errors::VSphereError", "The box is not able to report an address for WinRM to connect to yet.\nWinRM cannot access this Vagrant environment. Please wait for the\nVagrant environment to be running and try again."]
IS-mbp-rich2:vsphere rich$ vagrant global-status
id       name    provider   state     directory                                
-------------------------------------------------------------------------------
14e8f80  default vsphere    preparing /Users/rich/automation/vsphere           
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
IS-mbp-rich2:vsphere rich$ vagrant winrm 14e8f80 -c "ping google.com"

Pinging google.com [173.194.46.36] with 32 bytes of data:
Reply from 173.194.46.36: bytes=32 time=27ms TTL=51
Reply from 173.194.46.36: bytes=32 time=22ms TTL=51
Reply from 173.194.46.36: bytes=32 time=22ms TTL=51
Reply from 173.194.46.36: bytes=32 time=21ms TTL=51

Ping statistics for 173.194.46.36:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 21ms, Maximum = 27ms, Average = 23ms

Here is the Vagrantfile:

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = 'vsphere'
  config.vm.box_url = '/Users/rich/automation/vsphere/dummy/dummy.box'
  config.vm.communicator = "winrm"
  # You should be using the vagrant-windows Vagrant Plugin!
  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  #config.windows.halt_timeout = 30
  config.winrm.max_tries = 30

  config.vm.guest = :windows
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  # Ensure that all networks are set to private
  config.windows.set_work_network = true

  config.vm.provider :vsphere do |vsphere|
    # The host we're going to connect to
    vsphere.host = '10.50.13.111'                            

   # The host for the new VM
    vsphere.compute_resource_name = '10.50.13.110'            

    # The resource pool for the new VM
    vsphere.resource_pool_name = 'testPool'                    

    # The template we're going to clone        
    vsphere.template_name = 'WindowsTest'    

    # The name of the new machine
    vsphere.name = 'bingo'

    # vSphere login
    vsphere.user = 'root'                                    

    # vSphere password
    vsphere.password = 'vmware'                            

    # If you don't have SSL configured correctly, set this to 'true'
    vsphere.insecure = true                                    
  end
end

**Comment by mkuzmin** [comment] 2015-12-05 12:13
Duplicate of https://github.com/nsidc/vagrant-vsphere/issues/144

**Comment by michael-brandt-cu** [comment] 2016-01-21 17:11
Fixed with v1.6.0

**Closed by michael-brandt-cu** 2016-01-21 17:11 UTC
